# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Dendrogram', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end

end
